### ISSUE TITLE
A little typo in the calculations folder

### ISSUE THREAD

**Issue by valb21** [bpbond/srdb#107]
Hi,

I report a little error in the name of a file in the "calculations" folder.
"6040 Sawaswatchi jEnviBiol 2011" file should be named "6040 **Saraswathi** jEnviBiol 2011"

Source :

srdb-data-V4 (study number 6040)

https://search.proquest.com/openview/b6d1ad25a9bb5b7bafe13d58f1937a7b/1?pq-origsite=gscholar&cbl=636374

Regards

**Comment by bpbond** [comment]
Ugh, I wonder how that happened. Thank you.
