### ISSUE TITLE
NAs in Record_number 

### ISSUE THREAD

**Issue by mlkhorn** [bpbond/srdb#13]
We found two NAs in the record number column. This doesn't make sense. They are at indexes 3906 and 3907. See below for more information.  @bpbond Do you want to look at them?  

```
  Record_number Entry_date Study_number Author
          <int> <chr>             <int> <chr> 
1            NA 11/23/10           5417 Ruehr 
2            NA 11/23/10           5417 Ruehr 
```

**Comment by bpbond** [comment]
Thanks! They actually do have numbers--you can open the file and look. I suspect what's happening is that you're using `readr:read_csv` to parse the file, and (because of a problem now familiar to @kdorheim) the number is getting dropped.

**Comment by bpbond** [comment]
You can read us arguing about this with the `readr` folks here: https://github.com/tidyverse/readr/issues/645
