### ISSUE TITLE
Ecosystem_types to collapse

### ISSUE THREAD

**Issue by kendalynnm** [bpbond/srdb#130]
Studies with "Meadow" ecosystem_type -> "Grassland"
13018*
13079*
8249
8390

Studies with "Pasture" ecosystem_type -> "Grassland"
13189*

Studies with "Savannah" ecosystem_type -> "Savanna"
13242*

*Indicates studies from rs_synthesis project 2018+ google sheet

**Comment by bpbond** [comment]
Dealt with all of these in #137
