### ISSUE TITLE
Possible Study_number frameshift

### ISSUE THREAD

**Issue by kendalynnm** [bpbond/srdb#135]
Hi @bpbond,
After completing the DOI check for the rs-synthesis paper, I can confirm that there is a mismatch between Study_number in the google sheet and manuscript pdf titles in the Soil Respiration google drive and those being brought in by SRDB. The mismatch starts at Study_number 13000 (although that's relative to the studies included in rs-synthesis, so not an absolute). This could be an error initiated on the google drive end, but I don't have the first-hand experience for generating those files to say.
Happy to help dig into this further!

**Comment by bpbond** [comment]
I have investigated and don't believe this issue affects SRDB. Thank you!
