### ISSUE TITLE
Can not find Variables' Units 

### ISSUE THREAD

**Issue by tsinlu** [bpbond/srdb#136]
Say hello to respectable you! I met a question when I use this datasets, I can not find the variables' unit, which making it difficult for me to interpolate the data. So I wanna know where I can get the variables' units so that I can make sure my works' accuracy.

**Comment by bpbond** [comment]
Hi @tsinlu — you closed this issue, so I assume you found the documentation? But let me know if not.

**Comment by tsinlu** [comment]
@bpbond  Thank for your kind heart, I found the variables' units in srdb-data_fields.txt file. So I closed the issue, if It's a wrong way, please tell me.
