### ISSUE TITLE
Request for detail on soil properties

### ISSUE THREAD

**Issue by ldesousa** [bpbond/srdb#138]
Dear all,

I hope this is the right channel to pose these questions. Some of the soil properties in this dataset require further detail, namely:

- **C_soildepth** - is this the full depth of the soil, or can it be some arbitrary threshold?
- **Soil_BD** - does this field refer to the bulk density of whole soil, or only the fine earth fraction?
- **Soil_type** - to which classification system refers this field? Looks dissimilar to both the World Reference Base and the USDA soil taxonomy.

Thank you.

**Comment by bpbond** [comment]
Hello @ldesousa -

* See the [srdb-data_fields.txt](https://github.com/bpbond/srdb/blob/master/srdb-data_fields.txt) file: it's the depth corresponding to the `C_soilmineral` value, i.e. to which it was measured.
* Whatever convention the authors adopt. Usually I'd say it's whole soil.
* `Soil_type` is _extremely_ ad hoc; it's simply reporting what the authors report, and so it not standardized to any one taxonomy.

**Comment by bpbond** [comment]
Hope this has been resolved? Re-open if not please @ldesousa .
