### ISSUE TITLE
Incorrect lon/lat values

### ISSUE THREAD

**Issue by bpbond** [bpbond/srdb#2]
Yaxing Wei of ORNL points out there are many records in `srdb` with lon/lat problems, because
* The longitude and latitude were switched,
* The sign of one of the coordinates is wrong, or
* Unknown problem

Problem record numbers include: 128 536 1354 1355 2096 2116 2117 2118 2119 2120 2121 2122 2405 2406 2407 2408 2409 2410 2411 2412 2413 2414 2415 2416 3001 3002 3449 3450 3451 3452 3453 3454 3455 3456 3457 3458 3459 3460 3461 3462 3463 3464 3465 3605 3606 3607 3608 3609 3610 3611 3612 3613 3893 3894 4301 4302 4303 4304 4305 4306 4560 4770 4771 4772 4913 4932 4933 4934 4935 4936 4937 4938 4939 4940 4989 4990 4991 4992 4993 5124 5125 5126 5127 5128 5129 5130 5131 5132 5133 5134 5135 5136 5137 5138 5139 5140 5141 5142 5143 5144 5145 5146 5147 5148

**Comment by bpbond** [comment]
Fixed in commit 1b49161.

**Comment by ValentineHerr** [comment]
@bpbond, I spotted a couple issues in the coordinates of some sites:

Longitude sign is wrong for sites:

- Hontonin  (_record_number_ 6504)
- Tambopata- Candamo Reserve TAM05 (5911), longitude coordinates should actually be -69.27 to fall in Peru.


There is a problem with site Seyitler (_recrod_number_ 3435  and 3436), it should be in Turkey but coordinates fall in Japan.

**Comment by ValentineHerr** [comment]
For Seyitler the coordinates are probably around lat = 41.18 and , long =  41.82

**Comment by bpbond** [comment]
Thank you @ValentineHerr ! 👏
