### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by jinshijian** [bpbond/srdb#22]
**Three papers should correct latitude and longitude**
* Study number **143** -- latitude, longitude (41.08, 12.45, in sea) change to (41.13, 14.65), **reason**: Site description, Monte Taburno, Italy, Figure 1.
* Study number **1078** -- latitude, longitude (6.23, 2.08, in sea) change to (6.38, 2.13), **reason**: should be 6°23" and 2°08".
* Study number **3801** -- add  latitude, longitude as (30.03, 114.37), **reason**: According to the site description, the site located at Heshengqiao, Xianning, Hubei Provience.
* Study number **5184** -- add  latitude, longitude as (34.08, 133.29), **reason**: According to the site description, the site located at northwestern part of the Seto Inland Sea, Japan.
* Study number **5227** -- latitude, longitude (28.58, -16.60 in sea) change to (28.58, -27.25), **reason**: According to page 2, study site description.
* Study number **7530** -- longitude should be multiplied by -1, **reason**: According to table 1 in the paper.

**Comment by jinshijian** [comment]
**Another two paper**

* Study number **66** -- Nara site's latitude, longitude (32.00, 129.83, in sea, and faraway from Nara, Japan) change to (34.69, 135.83), **reason**: According to site description, this site located at Yugai Moutain, Nara, Japan.
* Study number **90** -- latitude, longitude (41.08, 12.45, in sea) change to (41.13, 14.65), **reason**: Site description, Monte Taburno, Italy, this paper wrote by same author as study number 143.

**Comment by jinshijian** [comment]
**Another one paper**
* Study number 6497 -- add latitude, longitude as (34.08, 133.29), **reason**: Site description, northwestern part of the Seto Inland Sea, Japan, and Figure 1 in the paper.

**Comment by jinshijian** [comment]
**Another one**
Study number **2325** -- change latitude, longitude from (48.30, -124.70, in sea) to (47.80, -123.60), **reason**: Site description, Olympic National Park, Washington, USA, and Figure 1 in the paper.

**Comment by jinshijian** [comment]
**Another issue for study Number 7530**
* For study **7530**, I forgot to mention that other than the *-1 issue, one Latitude = 4.051666667 should be changed to 40.517.

**Comment by jinshijian** [comment]
**Correction for Study Number 5227**
In the issue, I reported the change for study number 5227, but I found the paper reported wrong latitude and longitude information. That is to say, the latitude and longitude should change to  (28.29, -16.63).

**Comment by bpbond** [comment]
These are fantastic @jinshijian – thank you! Pushing up these changes to master.
