### ISSUE TITLE
Model type and units issue

### ISSUE THREAD

**Issue by jinshijian** [bpbond/srdb#23]
**1. Model_output_units issue**
* Model_output_units = 'gC/m2/hr' change to 'g C/m2/hr',
* Model_output_units = 'gC/m2/day' change to 'g C/m2/day'
* Model_output_units = 'mgC/m2/hr' change to 'mg C/m2/hr'
* Model_output_units = 'gCO2/m2/day' WHERE Model_output_units = 'g CO2/m2/day'
* Model_output_units = 'umolCO2/m2/s' WHERE Model_output_units = 'umol CO2/m2/s'

**2. Model_type and model parameter issue**

* Study number 1518, 2251
-- Model type change to 'R10 (L&T), R=a exp(b((1/c)-(1/(T-d))), T in K'

* Study number 3600
-- Model_Type should be: 'Linear, R=a+b(T-c)'
-- Model_paramA =-0.0909, Model_paramB =0.0366, Site_name = 'Mt_Kumdan_RF' (**Record_number  3253**)
-- Model_paramA =-0.0765, Model_paramB =0.0328 , Site_name = 'Mt_Kumdan_IF' (**Record_number  3254**)
-- Model_paramA =-0.1303, Model_paramB =0.0386 , Site_name = 'Mt_Kumdan_CS' (**Record_number  3255**)

* Study 4013 
-- Units change to mol C/m2/yr

* Study_number 8602
-- Model_type change to: "Q10, R=a b^((T-c)/10) "
-- Model_paramC should change to 10

* Study number 395
-- According to Table 3 in the paper
-- Model type should change to "Linear, R=a+b(T^2)"
-- Model_paramA change to 11 (record number 1655) and 31 (**record number 1656**)
-- Model_paramB change to 0.42 (record number 1655) and 0.58 (**record number 1656**)
-- Model_paramC change to NULL

* Study 6462
-- According to Table 3
-- Model type change to "R10 (L&T), R=a exp(b((1/c)-(1/T+d)) SWC"
-- Model_paramC shoube be 10, Model_paramD should be -46.02
-- Model in this study has a WTL component, add a flag?

* Study number 7290 
-- Model type change to "Exponential, R=a exp(b(T-c))" 
-- According to paper pg 4 description on formular (2), exp(Model_paramB * 10) = Q10, thus, Model_paramB = log(Q10)/10, thus, Model_paramB should change to 0.12282
-- Model_paramC change to 10

* Study 2560
-- Model type change to "Exponential, R=a exp(b(T-c))"

* Study number 8079
-- According to Figure 8 in the paper
-- Parameter D change to 0 (record number 6621)
-- The model for the forest cannot be used, because it is only for summer (Make a flag for record number 6622?)

* Study number 8382
-- According to table 2 and equation 1, model has a soil water content (SWC) component
-- Model type change to 'R10 (L&T), R=a exp(b((1/56.02)-1/(T-227.13)) exp(-exp(c-d SWC))' ?
-- Make a flag?

* Study number 109
-- According to Table 1
-- Model_type change to 'Power, R=c T^2'
-- Model_paramA, B, C, and D should be 0, 0, 0.0444, NULL

* Study number 390, 680, 1116
-- Model with SWC component, make a flag?

* Study number 1324
-- Model_type change to 'Exponential, R=a+b exp(T/c)'
-- The Model_paramB in the figure is not correct, I digitized the data, and use the same equation formate simulated the model, and get following values: 
-- Model_paramA, B, C, D change to 2.414, 7.483e-12, 1.176, NUL

* Study number 2182
-- According to Table 2
-- Model type change to "Exponential (other), ln(R)=a+b(T+d)+c(T+d)^2"
-- Model_paramD change to 10

* Study number 2325
-- According to Table 4
-- Model type change to "Exponential (ln1), ln(R)=a+b(T-c)"  (**Record number 1819 and 1820**)
-- Model type change to "Exponential (ln1), ln(R)=a+b(T-c)SWC" (**Record number 1821** with SWC component)

* Study number 2541
-- Model has SWC component, make a flag?

* Study number 3619
--Mmodel type change to "Exponential (other), R=a*b^(ct)"
-- Model_paramC change to 0.1

* Study number 4614
-- From table 1
-- Model type change to "Exponential, R=a exp(b(T-c))"

-- Study number 5162
-- According to equation 2 and table 4
-- Aodel type change to "Arrhenius, R=a*exp(b/c (1/d-1/T)), T in K"
-- Model_paramC = R = 8.134, Model_paramD = Tref = 283.16

* Study number 5227
-- According to Figure 8
-- Model type change to "Exponential (other), R=a*exp(ln(b (T-c)/c))" 

* Study number 7238 , Longitude wrong, should *-1
--According to Equation 1 in the paper
-- Model type change to 'Q10, R=a b^((T-c)/10)'
-- Model_parameC = Tb = 24 (section 2.5.1 in the paper)
-- Longitude should change from 75.75 to -75.75

* Study number 7695
--According to table 3 and equation 1
-- Model type change to "Exponential, R=a exp(b(T-c))"

* Study number 7727
-- According to Figure 2
-- Model type change to "Exponential, R=a exp(b(T-c))"

* Study number 8117
--According to Figure 5
-- Model type change to "Exponential, R=a exp(b(T-c))"

* Study number 8186
-- According to Table 3
-- Model type change to "Exponential, R=a exp(b(T-c))"

**Comment by bpbond** [comment]
>1. Model_output_units issue

Thanks–I'll make these changes for consistency. However, our script(s) should be smart enough to deal with this, e.g. by removing spaces:

```R
equation <- gsub(" ", "", equation)  # remove all spaces
```

**Comment by bpbond** [comment]
```
Study 6462
-- According to Table 3
-- Model type change to "R10 (L&T), R=a exp(b((1/c)-(1/T+d)) SWC"
-- Model_paramC shoube be 10, Model_paramD should be -46.02
-- Model in this study has a WTL component, add a flag?
```
Their Table 3 is pretty confusing, and ""R10 (L&T), R=a exp(b((1/c)-(1/T+d)) SWC" isn't a mathematically valid equation. Maybe we just enter "Other" here?

**Comment by bpbond** [comment]
```
Study 2560
-- Model type change to "Exponential, R=a exp(b(T-c))"
```
It already is this type (?).

**Comment by bpbond** [comment]
@jinshijian Added to new quality flags:

		Q15	seasonal model, not annual
		Q16	model has a soil water component or dependency
