### ISSUE TITLE
Model type and units issue 2

### ISSUE THREAD

**Issue by jinshijian** [bpbond/srdb#24]
**Study number 3733**
--# The author reported the model wrong in Fig 3, these models should be exponential model rather than power function
--# In the fig caption, the author said is exponential model, and if use exponential model, I got the same figure, if use the power function, it is way off from the figure
--# Model type shuld change to "Exponential, R=a exp(b(T-c))"
-- If use power model, take the first equation as an axample, it is like this
![image](https://user-images.githubusercontent.com/13302161/54239407-7ad38380-44f1-11e9-948e-a31b801302f9.png)
-- But use exponential model, it looks like this, it is similar to what reported in Fig3
![image](https://user-images.githubusercontent.com/13302161/54239461-a0f92380-44f1-11e9-9028-f265e7f1950b.png)

**Study number 5273**
--# According to description on page 2 of the paper, this model is just for the diurnal data
--# Add Q15 flag to it?

**Study number 5317**
--# According to Table 3 and description of Equation (1) 
--# Model_paramC = 10 (unit should be in C rather than K)
--# Model type shuld change to "R10 (L&T), R=a exp(b((1/(c-d))-(1/(T-d)))"

**Study number 5766**
--# According to Figure 4
--# Soil temperature is not in K
--# Model_type change to: "R10 (L&T), R=a exp(b((1/c)-(1/(T-d)))"

**Study number 6219**
--# According to table 2 and equation 7
--# Model_paramC change to 0

**Study number 6272**
--# Table 3 and 4, the unit in Figure 4 should be wrong
--# Unit change to "umol CO2/m2/s"

**Study number 6566**
--# According to Equation (8) in _J. Lloyd, J.A. Taylor, On the temperature dependence of soil respiration, Funct. Ecol. 8 (1994) 315 e 323._ , Equation (3) in this study is wrong
--# Model change to "R10 (L&T), R=a exp(b/((273.15+c)*8.314)*(1-(273.15+c)/T)), T in K"

**Study number 8866**
--# According to Table 1, unit here is wrong, because if plot it out (see the attached figure, RS value is pretty small, it should not be in "mg CO2/m2/hr", should be "g CO2/m2/hr" ?
--# Unit change to "g CO2/m2/hr"?

![image](https://user-images.githubusercontent.com/13302161/54239233-fd0f7800-44f0-11e9-9702-bce3f537ec21.png)

# Study 390, 680, 1116, 2514, 4155, 4212, 5184, 5216
--# Model has soil water content component.
-- # Add Q16 flag to it?

**Comment by bpbond** [comment]
> 2514

There is no study number 2514

Made all the other changes though. Thanks!

**Comment by bpbond** [comment]
P.S Great documentation, thanks. The graphs and explanations are really useful.
