### ISSUE TITLE
Model type and unit issue 3

### ISSUE THREAD

**Issue by jinshijian** [bpbond/srdb#25]
# 2541
-- 2514 I reported last time should be 2541, model with SWC component
# 3801
-- According to Table 3, Rs_Annual unit in paper is g co2/m2/yr
-- Rs_Annual unit in SRDB is g c/m2/yr, so Rs_Annual should change to Rs_Annual(original value)*12/44
-- Model_paramA, B change to 39.449, 0.0414 (record number = 3080)
-- Model_paramA, B change to 4.3737, 0.1018 (record number = 3081)
-- Model_paramA, B change to 11.301, 0.073 (record number = 3082)
-- Model_paramA, B change to 16.734, 0.0632 (record number = 3083)
# 5178
-- According to Figure 3 caption, model is based on data two years after haverst
-- Which means the model is for record number 3438, but may not suit for Record_Number = 3437, 3439, 3440, and 3441, change Model_paramA, B change to NULL for Record_Number = 3437, 3439, 3440, and 3441?
# Study 6372
-- According to Table 4, Model_paramB = 0.07231 for record_number = 4901
# Study 1292
-- According to Fig 4, Model_output_units = 'mg C/m2/hr'
# Study 3700
-- According to Fig 2 and FIg 3
-- Rs_annual = 590 when Record_number = 2444
-- Rs_annual = 1075 when Record_number = 2446
# Study 5227
-- The model reported in the paper is not correct, the model is: 2.49*exp(log(3.89 * (T-10)/10)), then when T < 10 there are no rs can be calculated, that not match the figure.
-- But I cannot figure it out what is the problem, I use the digitized data, re-simulated the exponential model
-- Model_type = 'Exponential, R=a exp(b(T-c))', Model_paramA = 0.573, Model_paramB = 0.0924, Model_paramC = 0
-- Longitude Wrong? I search 'Tenerife canary islands' in google, the location is 28.2916° , -16.6291°  
# Study number 6272
-- According to Fig 4 and Table 3, Pine Forest (PF, with Model_paramA=0.21) should has smallest Rs_annual
-- Rs_annual = 961 WHERE Record_number = 4794
-- Rs_annual = 833  WHERE Record_number = 4797
-- Rs_annual = 1166 WHERE Record_number = 4796
-- Rs_annual = 1158 WHERE Record_number = 4799
# Study 8569
-- Paper reported Rs_Annual in unit of g CO2/m2/yr, so Rs_annual should change to Rs_annual *12/44

**Comment by jinshijian** [comment]
# Study 5725
-- Model_paramA,B,C are not correct, based on the reported parameters, plot like this
![image](https://user-images.githubusercontent.com/13302161/54385081-299bcf00-466c-11e9-97f3-4afc81fd61b0.png)
-- which not match Fig 3
-- Based on the digitized data,  Model_paramA = -0.2189, Model_paramB = 0.0964, Model_paramC = -0.0025
![image](https://user-images.githubusercontent.com/13302161/54385818-e8a4ba00-466d-11e9-9875-d0a0821c0bd5.png)
-- Got a similar plot as Fig 3

**Comment by jinshijian** [comment]
-- I am sorry, I made a mistake on the units, now the figure is exactly same as Fig 3 in the paper
-- Model_paramA = -0.1226, Model_paramB = 0.054, Model_paramC = -0.0014
![image](https://user-images.githubusercontent.com/13302161/54387706-72ef1d00-4672-11e9-8062-a642c03e1fbf.png)

**Comment by jinshijian** [comment]
Study number **1078, 1292,1647,1871,1987,2372,2534,5278,5522,5701,6372,6381,6451** Annual_coverage should be **1**

**Comment by bpbond** [comment]
>-- Longitude Wrong? I search 'Tenerife canary islands' in google, the location is 28.2916° , -16.6291°

In the record it's -16.63. Do we need more precision so it doesn't land in the water?

**Comment by bpbond** [comment]
>-- I am sorry, I made a mistake on the units, now the figure is exactly same as Fig 3 in the paper

For 5725, do those new parameters apply to all the rows (records 4294-4299)?

**Comment by bpbond** [comment]
> 2534

Hmm. I wrote that one. 😆  It was a growing season-only measurement.

**Comment by bpbond** [comment]
>Study number 1078, 1292,1647,1871,1987,2372,2534,5278,5522,5701,6372,6381,6451 >Annual_coverage should be 1

See above comment. I'm going to stop for the moment, at 2534, for confirmation...these changes are for studies where they measured year-round?

Pushing other changes. Thanks!

**Comment by jinshijian** [comment]
# 5227
* 16.63 is good, we do not need to change it, it doesn't land in the water.
#5725
* Yes, those new parameters apply to all the rows (records 4294-4299), the two curves are very similar, and the paper does not report soil temperature for both sites, so I think it is fine to use the same parameters.
# Study number 1078, 1292,1647,1871,1987,2372,2534,5278,5522,5701,6372,6381,6451 Annual_coverage should be 1
* I have to double check this issue, as you mentioned, sometimes the annual Rs is estimated based on modeling, and sometimes one site has all year measurement, but not all sites.

**Comment by bpbond** [comment]
OK, making the 4294-4299 changes; let me know about the `Annual_coverage` issue.

**Comment by jinshijian** [comment]
# 1292
-- From Figure 1, Annual_coverage should be 1.
# 1647
-- From Figure 3, 5, and 6, Annual_coverage should be 1.
# 1871
-- Figure 7, Annual_coverage should be 1.
# 1987
-- According to Figure 6 and Figure 11, even though there are some gaps in each chamber, but six chambers together should have a good all year coverage, so Annual_coverage should be 1.
# 2372
-- According to Figure 2, Annual_coverage should be 1.
# 2534
-- Annual Rs was estimated according to modeling, Annual_coverage remain the same (0.35).
# 5278
-- From Figure 5, Annual_coverage should be 1.
# 5522
-- Estimated annual Rs, Annual_coverage remain the same (0.33).
# 5701 
-- According to Figure 2, measured 11 months, Annual_coverage should be 0.92
# 6372 
-- According to Figure 2, Annual_coverage should be 1.
# 6381
-- Estimated annual Rs, Annual_coverage remain the same (0.75).
# 6451
-- Some sites estimated annual Rs, Annual_coverage remain the same.
