### ISSUE TITLE
Database reorganization

### ISSUE THREAD

**Issue by bpbond** [bpbond/srdb#30]
1. Timing: @bpbond to integrate RM changes, google sheet, and existing `master`

2a. @jinshijian to add `Site_ID` and other fields (see below), along with mgrsd and hgrsd data

2b. New `Site_ID` (see https://github.com/forc-db/ForC_private/issues/22 but that's a private repo link). In theory `Study_number` + `Site_ID` + `Study_midyear` is UNIQUE

3. New students can, initially, help fill in fields like collar depth and survey time for older SRDB data

4. Break out parameter/Q10 data into their own table (see below)

5. This is where students will start from: simplified main SRDB table. It's also the version we'll call "v5" (in ORNL DAAC terminology), and write a ESSD paper about.

**Potential new fields**
* `Site_ID`
* Flags for daily/hourly/monthly data. Unclear, right now, if we want these flags (handy but duplicates information that can be gotten by joining tables), and where we want them (studies or data, for example). @bpbond and @jinshijian to think more about this
* `Collar_insert_depth` - for sure
* `Survey_time` - yes, but not sure how detailed. Categorical (Morning/Afternoon/Daytime/Nighttime)? Numerical (hours of start and end)? Think a little more about this

**Equations and Q10s for Rh and potentially Ra**
* Rh definitely; @bpbond a little unsure about Ra because it's almost never measured directly
* We could pull out all the equation fields into their own table. This would simplify the existing `srdb-data.csv`, and let us have a new table, `equations.csv` that has (e.g.) some link to main table (think about this), `Flux` (Rs, Rh, or Ra), and then parameter and Q10 information and SWC response (maybe equation, need to think)

**Comment by bpbond** [comment]
Think about adding a `SOC_percent` field, to complement existing `C_soilmineral` one.

**Comment by bpbond** [comment]
The first step here (integrating RM data) is going a bit slow than I expected, but it's going.

**Comment by bpbond** [comment]
Update: I believe I have cleaned up all duplication, etc., on `master`, but there are a number of issues ( #35 #36 #37 #38 ). Need to resolve these, assign `Record_number` column, and then deal with `Site_ID`.

**Comment by jinshijian** [comment]
Hello Ben,

Sounds great, I apologize for the problem, I will take a look at those
issues.

Thanks,
Jinshi
