### ISSUE TITLE
11861 Ng no data

### ISSUE THREAD

**Issue by bpbond** [bpbond/srdb#38]
These rows are identical because there's no flux or sensitivity data.

**Comment by jinshijian** [comment]
Study Number 5836, 11861, and 11950 have this issue.
# 5836 - study only reported Heterotrophic respiration from Feb 08 to Aug 08 (so Rs_annual or Rh_annual are not available), I have this information in the MGRsD, to guarantee MGRsD and srdb can be linked, I added it to SRDB.
#  11861 - Study only reported Rs from Day-of-year 200 to Day-of-year 360 (so Rs_annual cannot directly get), same reason, I added to srdb to guarantee the linkage between MGRsD and srdb.
# 11950 - Study only reported 5 days diurnal Rs (So Rs_annual are not available), I have this study in HGRsD, I added it to guarantee the linkage between HGRsD and srdb.

In the future, MGRsD and HGRsD will only include studies appeared in srdb, so this issue will not be a problem in the future. For these three studies, can we discuss tomorrow should we keep them or delete them?

**Comment by bpbond** [comment]
Hmm, ok, thanks. No I think they're fine in this case.
