### ISSUE TITLE
1716 Wang genus/species missing (common names given)

### ISSUE THREAD

**Issue by bpbond** [bpbond/srdb#39]

**Comment by jinshijian** [comment]
Author information should be "Yang"
Annual grasses and blue oak --> herbaceous, Quercus douglasi
Ponderosa pine, white fir --> Pinus ponderosa, Abies concolor
Western white pine --> Pinus strobus
Lemon trees --> Citrus limon (L.) Osbeck

**Comment by bpbond** [comment]
Thanks! This will close with #42
