### ISSUE TITLE
11817 Zhao manipulation

### ISSUE THREAD

**Issue by bpbond** [bpbond/srdb#40]
What does "Frenched" mean?

**Comment by bpbond** [comment]
Also in 11822 Li

**Comment by jinshijian** [comment]
Sorry, it should be 'Fenced'. It is a type of forest/grassland protect policy in China (maybe also exist in the USA), where graze or human activity will be forbidden or limited (sometimes will have an actual fence, but sometimes only have some signs and bands), please replace the word if 'Fenced' is not appropriate.

**Comment by bpbond** [comment]
Thanks. This will be closed by merging #42
