### ISSUE TITLE
11756 Den partition method

### ISSUE THREAD

**Issue by bpbond** [bpbond/srdb#41]
What is "Root remove"? Is it different from trenching?

**Comment by jinshijian** [comment]
The difference between "Root remove" and "trenching" is "Root remove" will strip the soil, take the roots away, and then refill the soil back. But I notice that we have only one study with "Root remove" partition method, we can change it to "trench" or "bare soil".

**Comment by bpbond** [comment]
Assuming it isn't "Extraction" (measuring from extracted roots), then let's stick with "Exclusion", which is the established term. Thanks.

**Comment by jinshijian** [comment]
Sounds good
