### ISSUE TITLE
Quality_flag

### ISSUE THREAD

**Issue by jinshijian** [bpbond/srdb#51]
Hey Ben, do you added two quality flags (Q15 and Q16) in the Quality_flag? Should you update the srdb_data_field description and add a description about Q15 and Q16?

**Comment by bpbond** [comment]
I don't think I added anything new.

**Comment by jinshijian** [comment]
I guess is when we working on Bahn's paper, we found some Rs equations are not for annual, but for the growing season (Q15?), and another one is equation have soil water content component (Q16?).
