### ISSUE TITLE
Meeting notes with Nazar

### ISSUE THREAD

**Issue by jinshijian** [bpbond/srdb#64]
Hello, Ben

Here are some notes for today's meeting with Nazar, please add if I missing something.

* Russia paper from SRDB (both in Russia all located in Russia) summary.
* Keywords for searching papers.
* Criteria for a paper should be considered.
* Provide necessary SRDB related information (study list, srdb explanation, etc).

**Comment by bpbond** [comment]
Thanks! Sent info to Nazar.

**Comment by bpbond** [comment]
Today's meeting - Nazar will continue with searching publications through the end of 2019. We'll reconvene in early 2020 and plan moving to data entry.

[Russian publications.xlsx](https://github.com/bpbond/srdb/files/3919637/Russian.publications.xlsx)
