### ISSUE TITLE
Trouble reading figure in 9695.

### ISSUE THREAD

**Issue by jmanzon** [bpbond/srdb#68]
Please take a look at figure 4 in 9695. Gives information on Rs, Ra, and Rh.

**Comment by bpbond** [comment]
Agreed, that's confusing. I'd suggest using DataThief to take the average of the two Rs lines, and call that `Rs_growingseason`, with `Study_midyear` of 2012.5 and `YearsOfData` equal to 3. We can make a note about the Rh_growingseason, for which we don't currently have a field.

**Comment by bpbond** [comment]
I assume this can be closed at this point.
