### ISSUE TITLE
A potential issue in study number 9549

### ISSUE THREAD

**Issue by jinshijian** [bpbond/srdb#73]
Hello Ben, 

The Rs data reported by the author may have the wrong unit, can you please double-check? 
The units for Rs_annual is kg CO2-C/ha/yr in Figure 3.
The value seems extremely low.
In table 4, they reported the seasonal Rs rate, I calculated the Rs_annual from seasonal rate, and there is a big mismatch.
So I used the results from the seasonal Rs rate (because it is more reasonable).

Thanks
Jinshi

**Comment by jinshijian** [comment]
And/or make a data quality flag for this study.

**Comment by bpbond** [comment]
Hmm, Table 4 is methane. Table 3 is CO2, and averaging those number I get about 6-8 kgC/ha/d or 220-300 gC/m2/yr? That seems consistent with the figures (?).

**Comment by jinshijian** [comment]
I mean Table 3, I typed it wrong before.
But the unit in Figure 5 is Kg C / ha /yr. The number need times 0.1 to get gC/m2/yr.

**Comment by bpbond** [comment]
Ah I see. Yes, they must have made a mistake in Figure 5? I agree, we should use the averaged seasonal rate.
