### ISSUE TITLE
Some Rs information could be skipped when collecting data from paper into SRDB

### ISSUE THREAD

**Issue by jinshijian** [bpbond/srdb#79]
Hello Ben, since detailed Rs (daily and hourly) will be included in the MGRsD and HGRsD, I think when we collect the data, we do not need to collect Rs_max,Rs_maxday, Rs_min, Rs_minday, Rs_spring, Rs_summer, Rs_autumn, Rs_winter, and Rs_growingseason, do you agree? If you agree, I will tell Jason and Darlin to skip those columns to save some time (those data usually need to read through Datathief, it is time-consuming).

**Comment by bpbond** [comment]
I agree. I'd be open to drop the columns entirely from the database.

**Comment by jinshijian** [comment]
Could keep Rs_growingseason, it is commonly reported.

**Comment by bpbond** [comment]
Agreed on `Rs_growingseason`. Do we want to remove them from SRDB now?

**Comment by jinshijian** [comment]
I agree to remove those columns, I have told Jason and Darlin not to record
that information in the google sheet. So it will be helpful to delete those
columns in the google sheet as well. Thanks

**Comment by jinshijian** [comment]
I have a pull request, should we merge the changes from the branch first, or it does not matter?

**Comment by bpbond** [comment]
Update: we're going to delete Rs_max, maxday, min, minday, leaving others for now.
