### ISSUE TITLE
Text from GlobalC appropriate for ESSD

### ISSUE THREAD

**Issue by bpbond** [bpbond/srdb#82]
Heterotrophic respiration from ESMs heavily depends on SOC, the importance of SOC in the Rh computation might be overestimated. The relationship between SOC and Rh need to be tested using site measurements 38; currently, SRDB collected carbon concentration information (whenever soil carbon was reported as g C m-2), but many studies reported soil carbon stock (in the unit of %, i.e., g C per 100 g soil), compiling site soil carbon information into SRDB and a meta-analysis is important to explore the importance of SOC in the Rh computation in the ESMs models.

**Comment by jinshijian** [comment]
Incorporated into ESSD manuscript
