### ISSUE TITLE
2676 longitude

### ISSUE THREAD

**Issue by jinshijian** [bpbond/srdb#85]
longitude in 2676 should be 116.68

**Comment by bpbond** [comment]
Hmm, that's what it seems to be already?

![Screen Shot 2020-04-02 at 2 57 45 AM](https://user-images.githubusercontent.com/1956468/78219561-c3a80280-748d-11ea-8ee3-554d01734fc0.png)

**Comment by bpbond** [comment]
@jinshijian Close this?

**Comment by jinshijian** [comment]
Ok, yes
