### ISSUE TITLE
Problems with v5 import data

### ISSUE THREAD

**Issue by bpbond** [bpbond/srdb#87]
- [x] 10031: entered by @jinshijian in 2020 but also by RM in 2019
- [x] 10078: entered by @jinshijian in 2020 but also by RM in 2019
- [X] 10079: was marked as "N" for DE; changed
- [X] 10085: marked as rank 3, not DL; should be 10885. Corrected
- [X] 10924: marked as not downloaded, should be 10942. Corrected
- [X] 2747: on 2020-01-21 @jinshijian entered "2747 Pumpanen" . I can't find the PDF anywhere for this. Database shows this as a duplicate of 2746 Pumpanen, already entered by @bpbond in 2012
- [X] 8185: database showed this as already entered 😕 but doesn't seem like it. Corrected
- [X] 8477: database shows not downloaded. By author name should be 8744; corrected in PDF name and data
- [X] 8751: pdf is kim but database shows Gilling author. By title, this is actually 8871 but this is a dupe of 8585 (correctly marked as a duplicate in data sheet). Changed study number to 8871 to match studies file
- [X] 8768: should be 8786, fixed
- [X] 9248: entered as 9248 by @darlinp but already marked N; should be 9258. Corrected
- [X] 9727: marked as not downloaded. Checked, should be 9327. Corrected

**Comment by bpbond** [comment]
@jinshijian See first two problems above, re studies 10031 and 10078. I'm attaching the relevant data here; could you take a look and see which we want to keep, and/or combine?
 
[Archive.zip](https://github.com/bpbond/srdb/files/4450965/Archive.zip)

**Comment by jinshijian** [comment]
* 10031
Using RM inputs, but delete Rs_annual and Rs_annual_err (because it is growing season Rs, not annual), Time_of_day is: 8to10

**Comment by jinshijian** [comment]
# 10078
Combing Chamber_area and Time_of_day from JJ to RM, and keep RM inputs

**Comment by jinshijian** [comment]
* 2747
This study is in srdb-studies.csv, and it has Rs_annual data. So I added it into the database.

**Comment by jinshijian** [comment]
@bpbond, this is checked by the 'srdb_check.R' script, right? It is awesome! I should describe this in the manuscript.

**Comment by jinshijian** [comment]
@bpbond  Can you please also make a note that 4309 and 4185 are duplicate

**Comment by bpbond** [comment]
OK, done. Thanks.
