### ISSUE TITLE
Partition_method

### ISSUE THREAD

**Issue by bpbond** [bpbond/srdb#88]
See list in #86 - there are two entries in `Partition_method` that are new.

First, "DeepPVC". Is there any reason not to rename this as "Exclusion", matching others in database?

Second, "EC". What is this? Eddy covariance? 

More generally

```R
> table(srdb$Partition_method)

               Comparison      deepPVC      DeepPVC     Equation     Excision    Exclusion   Extraction          GAP 
        8612          137            5          158            4            4          931          174            3 
      Girdle     Girdling      Isotope Mass balance     Mesh bag        Model        Other  Radiocarbon   Regression 
          11           10           66            5            6           28           41            2           16 
 Root remove  Subtraction         TBCA     Temporal 
           1           81           15            1 
```

- [X] DeepPVC and deepPVC -> Exclusion
- [X] Girdle -> Girdling
-  [x] @jinshijian can you check 11756 Den which was entered as "Root remove". Can we change this to Exclusion (roots excluded) or Extraction (soil extracted and measured root-free)?
- [X] GAP -> Comparison
- [X] Mesh bag -> Extraction
- [X] Equation -> EC

**Comment by jinshijian** [comment]
deepPVC: it is ok rename as "Exclusion".
EC: which study number has partition as "EC"? I do not see it.
Root remove: (did you deleted papers in the google driver?), I went to the dropbox, did not find the pdf for 11756 as well. But I think it is ok to include as "Exclusion".

**Comment by bpbond** [comment]
OK. Yes, sorry, I was doing some cleanup on the drive and removed papers.
